drop table note_log cascade constraints;
/

create table note_log
(
    id int generated by default as identity (start with 1 increment by 1) not null,
    id_nota int,
    vechea_valoare int,
    noua_valoare int,
    tipul_operatiei varchar2(100),
    data_operatiei date,
    executor varchar2(100),
    primary key(id)
);
/

create or replace trigger note_log_insert
    after insert on note for each row
declare
v_current_user varchar2(100);
begin
    select user into v_current_user from dual;
    insert into note_log (id_nota, vechea_valoare, noua_valoare, tipul_operatiei, data_operatiei, executor) values (:NEW.id, :OLD.valoare, :NEW.valoare, 'insert', sysdate, v_current_user);
end;
/

create or replace trigger note_log_update
    after update on note for each row
declare
v_current_user varchar2(100);
begin
    select user into v_current_user from dual;
    insert into note_log (id_nota, vechea_valoare, noua_valoare, tipul_operatiei, data_operatiei, executor) values (:NEW.id, :OLD.valoare, :NEW.valoare, 'update', sysdate, v_current_user);
end;
/

create or replace trigger note_log_delete
    after delete on note for each row
declare
v_current_user varchar2(100);
begin
    select user into v_current_user from dual;
    insert into note_log (id_nota, vechea_valoare, noua_valoare, tipul_operatiei, data_operatiei, executor) values (:OLD.id, :OLD.valoare, :NEW.valoare, 'delete', sysdate, v_current_user);
end;
/

insert into note values (16531, 1025, 25, 10, sysdate, sysdate, sysdate);
/

update note set valoare = 9 where id=16531;
/

delete from note where id=16530;
/


